"""add password_hash to users

Revision ID: 0db7fa0cb622
Revises: 562ebdbf63e0
Create Date: 2026-08-24 18:34:40.094821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db7fa0cb622'
down_revision: Union[str, None] = '562ebdbf63e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default is required here because NOT NULL columns can't be added
    # to a table with existing rows without one. This is a breaking change for
    # auth anyway - any pre-existing users have no real password and must sign
    # up again; the placeholder just lets the migration run without crashing
    # on teammates' existing local databases.
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False, server_default='reset-required'))
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('password_hash', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
