"""add user role and ticket resolved_at for municipal analytics

Revision ID: dc398db04c51
Revises: 12f96dd51791
Create Date: 2026-08-25 11:06:40.204704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc398db04c51'
down_revision: Union[str, None] = '12f96dd51791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('tickets', 'resolved_at')
    # ### end Alembic commands ###
